@host = http://localhost:5012

@sellerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjRjYTg3NGI4LWE0ZjQtNGE3NS1hMmJmLWEzYzQ3MzFjNzMyNCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InNlbGxlckB0ZXN0LmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJKYW51c3ogQml6bmVzdSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlNlbGxlciIsImV4cCI6MTc4MDQzMzIzOCwiaXNzIjoiR2FtZVN0b3JlLmFwaSIsImF1ZCI6IkdhbWVTdG9yZS5jbGllbnQifQ.abrSZED_mE8Sn4reQv1VkUHEXWkqVh70bKX8xu9cmck
@buyerToken = YOUR_BUYER_TOKEN_HERE

### Register Seller
POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "seller@test.com",
  "displayName": "Janusz Biznesu",
  "password": "Password123!",
  "role": "Seller"
}

### Register Buyer
POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "buyer@test.com",
  "displayName": "Kowalski",
  "password": "Password123!",
  "role": "Buyer"
}

### Login Seller
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "seller@test.com",
  "password": "Password123!"
}

### Login Buyer
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "buyer@test.com",
  "password": "Password123!"
}

### Search RAWG for games (Requires: SellerToken)
GET {{host}}/rawg/search?query=witcher
Authorization: Bearer {{sellerToken}}

### Import game from RAWG (Requires: SellerToken)
POST {{host}}/rawg/import
Authorization: Bearer {{sellerToken}}
Content-Type: application/json

{
  "rawgId": 3328
}

###
DELETE {{host}}/games/1
Authorization: Bearer {{sellerToken}}

### Get all games — paginated (Public)
GET {{host}}/games?page=1&pageSize=10

### Get games — filtered by genre (Public)
GET {{host}}/games?genreId=3

### Get games — search by title (Public)
GET {{host}}/games?search=witcher

### Get games — sorted by release date descending (Public)
GET {{host}}/games?sortBy=releaseDate&sortOrder=desc

### Get game details (Public)
GET {{host}}/games/1

### Add game to catalog manually (Requires: SellerToken)
POST {{host}}/games
Authorization: Bearer {{sellerToken}}
Content-Type: application/json

{
  "title": "Moja Gra",
  "description": "Opis gry",
  "genreId": 1,
  "imageUrl": "https://example.com/image.jpg",
  "releaseDate": "2024-01-01"
}

### Add offer (Requires: SellerToken)
POST {{host}}/games/1/offers
Authorization: Bearer {{sellerToken}}
Content-Type: application/json

{
  "price": 149.99,
  "stock": 10
}

### Get offers for a game (Public)
GET {{host}}/games/1/offers

### Update offer (Requires: SellerToken)
PUT {{host}}/games/1/offers/1
Authorization: Bearer {{sellerToken}}
Content-Type: application/json

{
  "price": 1.00,
  "stock": 0
}

### Delete offer (Requires: SellerToken)
DELETE {{host}}/games/1/offers/1
Authorization: Bearer {{sellerToken}}

### Place order (Requires: BuyerToken)
POST {{host}}/orders
Authorization: Bearer {{buyerToken}}
Content-Type: application/json

{
  "items": [
    { "gameOfferId": 1, "quantity": 3 }
  ]
}

### Get buyer orders (Requires: BuyerToken)
GET {{host}}/orders
Authorization: Bearer {{buyerToken}}

### Get order details (Requires: BuyerToken)
GET {{host}}/orders/1
Authorization: Bearer {{buyerToken}}

### Cancel order (Requires: BuyerToken)
POST {{host}}/orders/1/cancel
Authorization: Bearer {{buyerToken}}

### Get all genres (Public)
GET {{host}}/genres
